api_hash: xxxxxxxx
api_id: xxxxxxxx
chat_id: xxxxxxxx
disable_syslog:
- INFO
file_formats:
  video:
  - mp4
file_name_exclude:
- 电报搜
- 收藏夹
- 搜索
file_path_prefix:
- chat_title
hide_file_name: true
ids_to_retry: []
last_read_message_id: 0
max_concurrent_transmissions: 10
media_types:
- video
save_path: F:\telegram_media_downloader
